DISCOVERED_PAIRS = [
    ("Dr. Dre", "Eminem"),
    ("Dr. Dre", "Kendrick Lamar"),
    ("Dr. Dre", "Snoop Dogg"),
    ("Dr. Dre", "50 Cent"),
    ("Dr. Dre", "The Game"),
    ("Dr. Dre", "Anderson .Paak"),
    ("Jay-Z", "Rihanna"),
    ("Jay-Z", "Kanye West"),
    ("Jay-Z", "J. Cole"),
    ("Kanye West", "Chance the Rapper"),
    ("Kanye West", "Big Sean"),
    ("Kanye West", "Pusha T"),
    ("Kanye West", "Travis Scott"),
    ("Timbaland", "Justin Timberlake"),
    ("Timbaland", "Missy Elliott"),
    ("Timbaland", "Aaliyah"),
    ("Pharrell Williams", "Justin Bieber"),
    ("Pharrell Williams", "Snoop Dogg"),
    ("Rick Rubin", "Run-D.M.C."),
    ("Rick Rubin", "LL Cool J"),
    ("Rick Rubin", "Beastie Boys"),
    ("Berry Gordy", "Michael Jackson"),
    ("Berry Gordy", "Diana Ross"),
    ("Berry Gordy", "Stevie Wonder"),
    ("Berry Gordy", "The Jackson 5"),
    ("Quincy Jones", "Michael Jackson"),
    ("Simon Cowell", "One Direction"),
    ("Simon Cowell", "Leona Lewis"),
    ("L.A. Reid", "Usher"),
    ("L.A. Reid", "TLC"),
    ("L.A. Reid", "OutKast"),
    ("Sylvia Rhone", "Missy Elliott"),
    ("Puff Daddy", "The Notorious B.I.G."),
    ("Puff Daddy", "Usher"),
    ("Suge Knight", "Tupac Shakur"),
    ("Suge Knight", "Dr. Dre"),
    ("Ludacris", "Shawnna"),
    ("Nicki Minaj", "Lil Wayne"),
    ("Lil Wayne", "Drake"),
    ("Lil Wayne", "Nicki Minaj"),
    ("Drake", "PartyNextDoor"),
    ("Drake", "Roy Woods"),
    ("Metro Boomin", "21 Savage"),
    ("DJ Khaled", "Rihanna"),
    ("Elton John", "Ed Sheeran"),
    ("Elton John", "Kiki Dee"),
    ("Madonna", "Justin Timberlake"),
    ("Beyonce", "Chloe x Halle"),
    ("Ariana Grande", "Victoria Monet"),
    ("Justin Timberlake", "Shawn Mendes"),
    ("Usher", "Justin Bieber"),
]